from tkinter import *
class myEntry:
    def_init_(self,'root')
          self.f=Frame(root,height=350,width=500)
          self.f.pack()
          self.l1=Label(Text="enter user name:")
          self.l2=Label(Text"enter password")
          self.el=Entry(self.f,width=25,fg='blue',bg='yellow',font=("arial",14))
          self.e2=Entry(self.f,width=25,fg='blue',bg="yellow",show="*")
          self.e2.blind("<return>",self.display)
          self.l1.place(x=50,y=100)
          self.el.place(x=200,y=100)
          self.l2.place(x=50,y=150)
          self.e2.place(x=200,y=150)
          str1=self.e1.get()
          str2=self.e2.get()
          lbl1=Label(Text='your name is:'+str1).place=(x=50,y=200)
          lbl2=Label(Text='your password is:'+str2).place(x=50,y=220)
          root=Tk()
          mb=myEntry(root)
          root.mainloop()